# 单行代码的最大宽度
printWidth: 80
# 使用制表符 (tab) 缩进行而不是空格 (space)
useTabs: false
# 指定每个缩进级别的空格数
tabWidth: 2
# 在语句末尾打印分号
semi: true
# 使用单引号而不是双引号
singleQuote: false
# 换行格式
endOfLine: lf

overrides:
  - files: "*.html"
    options: 
      printWidth: 150
      tabWidth: 4